/*
** -----------------------------------------------------------------------------
** Copyright 1998-2012 Randy Heit
** All rights reserved.
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions
** are met:
**
** 1. Redistributions of source code must retain the above copyright
**    notice, this list of conditions and the following disclaimer.
** 2. Redistributions in binary form must reproduce the above copyright
**    notice, this list of conditions and the following disclaimer in the
**    documentation and/or other materials provided with the distribution.
** 3. The name of the author may not be used to endorse or promote products
**    derived from this software without specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
** IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
** OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
** IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
** INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
** NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
** THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** -----------------------------------------------------------------------------
*/

/*
Copyright (C) 2022 ***REMOVED***

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#[repr(u16)]
pub(super) enum PCode {
	NoOp,
	Terminate,
	Suspend,
	PushNumber,
	LSpec1,
	LSpec2,
	LSpec3,
	LSpec4,
	LSpec5,
	LSpec1Direct,
	LSpec2Direct,
	LSpec3Direct,
	LSpec4Direct,
	LSpec5Direct,
	Add,
	Subtract,
	Multiply,
	Divide,
	Modulus,
	Eq,
	Ne,
	Lt,
	Gt,
	Le,
	Ge,
	AssignScriptVar,
	AssignMapVar,
	AssignWorldVar,
	PushScriptVar,
	PushMapVar,
	PushWorldVar,
	AddScriptVar,
	AddMapVar,
	AddWorldVar,
	SubScriptVar,
	SubMapVar,
	SubWorldVar,
	MulScriptVar,
	MulMapVar,
	MulWorldVar,
	DivScriptVar,
	DivMapVar,
	DivWorldVar,
	ModScriptVar,
	ModMapVar,
	ModWorldVar,
	IncScriptVar,
	IncMapVar,
	IncWorldVar,
	DecScriptVar,
	DecMapVar,
	DecWorldVar,
	Goto,
	IfGoto,
	Drop,
	Delay,
	DelayDirect,
	Random,
	RandomDirect,
	ThingCount,
	ThingCountDirect,
	TagWait,
	TagWaitDirect,
	PolyWait,
	PolyWaitDirect,
	ChangeFloor,
	ChangeFloorDirect,
	ChangeCeiling,
	ChangeCeilingDirect,
	Restart,
	AndLogical,
	OrLogical,
	AndBitwise,
	OrBitwise,
	EOrBitwise,
	NegateLogical,
	LShift,
	RShift,
	UnaryMnus,
	IfNotGoto,
	LineSide,
	ScriptWait,
	ScriptWaitDirect,
	ClearLineSpecial,
	CaseGoto,
	BeginPrint,
	EndPrint,
	PrintString,
	PrintNumber,
	PrintCharacter,
	PlayerCount,
	GameType,
	GameSkill,
	Timer,
	SectorSound,
	AmbientSound,
	SoundSequence,
	SetLineTexture,
	SetLineBlocking,
	SetLineSpecial,
	ThingSound,
	EndPrintBold,
	ActivatorSound,
	LocalAmbientSound,
	SetLineMonsterBlocking,
	PlayerBlueSkull,
	PlayerRedSkull,
	PlayerYellowSkull,
	PlayerMasterSkull,
	PlayerBlueCard,
	PlayerRedCard,
	PlayerYellowCard,
	PlayerMasterCard,
	PlayerBlackSkull,
	PlayerSilverSkull,
	PlayerGoldSkull,
	PlayerBlackCard,
	PlayerSilverCard,
	IsNetworkGame,
	PlayerTeam,
	PlayerHealth,
	PlayerArmorPoints,
	PlayerFrags,
	PlayerExpert,
	BlueTeamCount,
	RedTeamCount,
	BlueTeamScore,
	RedTeamScore,
	IsOneFlagCtf,
	LSpec6,
	LSpec6Direct,
	PrintName,
	MusicChange,
	ConsoleCommandDirect,
	ConsoleCommand,
	SinglePlayer,
	FixedMul,
	FixedDiv,
	SetGravity,
	SetGravityDirect,
	SetAirControl,
	SetAirControlDirect,
	ClearInventory,
	GiveInventory,
	GiveInventoryDirect,
	TakeInventory,
	TakeInventoryDirect,
	CheckInventory,
	CheckInventoryDirect,
	Spawn,
	SpawnDirect,
	SpawnSpot,
	SpawnSpotDirect,
	SetMusic,
	SetMusicDirect,
	LocalSetMusic,
	LocalSetMusicDirect,
	PrintFixed,
	PrintLocalized,
	MoreHudMessage,
	OptHudMessage,
	EndHudMessage,
	EndHudMessageBold,
	SetStyle,
	SetStyleDirect,
	SetFont,
	SetFontDirect,
	PushByte,
	LSpec1DirectB,
	LSpec2DirectB,
	LSpec3DirectB,
	LSpec4DirectB,
	LSpec5DirectB,
	DelayDirectB,
	RandomDirectB,
	PushBytes,
	Push2Bytes,
	Push3Bytes,
	Push4Bytes,
	Push5Bytes,
	SetThingSpecial,
	AssignGlobalVar,
	PushGlobalVar,
	AddGlobalVar,
	SubGlobalVar,
	MulGlobalVar,
	DivGlobalVar,
	ModGlobalVar,
	IncGlobalVar,
	DecGlobalVar,
	FadeTo,
	FadeRange,
	CancelFade,
	PlayMovie,
	SetFloorTrigger,
	SetCeilingTrigger,
	GetActorX,
	GetActorY,
	GetActorZ,
	StartTranslation,
	TranslationRange1,
	TranslationRange2,
	EndTranslation,
	Call,
	CallDiscard,
	ReturnVoid,
	ReturnVal,
	PushMapArray,
	AssignMapArray,
	AddMapArray,
	SubMapArray,
	MulMapArray,
	DivMapArray,
	ModMapArray,
	IncMapArray,
	DecMapArray,
	Dup,
	Swap,
	WriteToIni,
	GetFromIni,
	Sin,
	Cos,
	VectorAngle,
	CheckWeapon,
	SetWeapon,
	TagString,
	PushWorldArray,
	AssignWorldArray,
	AddWorldArray,
	SubWorldArray,
	MulWorldArray,
	DivWorldArray,
	ModWorldArray,
	IncWorldArray,
	DecWorldArray,
	PushGlobalArray,
	AssignGlobalArray,
	AddGlobalArray,
	SubGlobalArray,
	MulGlobalArray,
	DivGlobalArray,
	ModGlobalArray,
	IncGlobalArray,
	DecGlobalArray,
	SetMarineWeapon,
	SetActorProperty,
	GetActorProperty,
	PlayerNumber,
	ActivatorTid,
	SetMarineSprite,
	GetScreenWidth,
	GetScreenHeight,
	ThingProjectile2,
	StrLen,
	SetHudSize,
	GetCVar,
	CaseGotoSorted,
	SetResultValue,
	GetLineRowOffset,
	GetActorFloorZ,
	GetActorAngle,
	GetSectorFloorZ,
	GetSectorCeilingZ,
	LSpec5Result,
	GetSigilPieces,
	GetLevelInfo,
	ChangeSky,
	PlayerInGame,
	PlayerIsBot,
	SetCameraToTexture,
	EndLog,
	GetAmmoCapacity,
	SetAmmoCapacity,
	PrintMapCharArray,
	PrintWorldCharArray,
	PrintGlobalCharArray,
	SetActorAngle,
	GrabInput,
	SetMousePointer,
	MoveMousePointer,
	SpawnProjectile,
	GetSectorLightLevel,
	GetActorCeilingZ,
	SetActorPosition,
	ClearActorInventory,
	GiveActorInventory,
	TakeActorInventory,
	CheckActorInventory,
	ThingCountName,
	SpawnSpotFacing,
	PlayerClass,
	AndScriptVar,
	AndMapVar,
	AndWorldVar,
	AndGlobalVar,
	AndMapArray,
	AndWorldArray,
	AndGlobalArray,
	EOrScriptVar,
	EOrMapVar,
	EOrWorldVar,
	EOrGlobalVar,
	EOrMapArray,
	EOrWorldArray,
	EOrGlobalArray,
	OrScriptVar,
	OrMapVar,
	OrWorldVar,
	OrGlobalVar,
	OrMapArray,
	OrWorldArray,
	OrGlobalArray,
	LSScriptVar,
	LSMapVar,
	LSWorldVar,
	LSGlobalVar,
	LSMapArray,
	LSWorldArray,
	LSGlobalArray,
	RSScriptVar,
	RSMapar,
	RSWorldVar,
	RSGlobalVar,
	RSMapArray,
	RSWorldArray,
	RSGlobalArray,
	GetPlayerInfo,
	ChangeLevel,
	SectorDamage,
	ReplaceTextures,
	NegateBinary,
	GetActorPitch,
	SetActorPitch,
	PrintBind,
	SetActorState,
	ThingDamage2,
	UseInventory,
	UseActorInventory,
	CheckActorCeilingTexture,
	CheckActorFloorTexture,
	GetActorLightLevel,
	SetMugShotState,
	ThingCountSector,
	ThingCountNameSector,
	CheckPlayerCamera,
	MorphActor,
	UnmorphActor,
	GetPlayerInput,
	ClassifyActor,
	PrintBinary,
	PrintHex,
	CallFunc,
	SaveString,
	PrintMapCHRange,
	PrintWorldCHRange,
	PrintGlobalCHRange,
	StrCpyToMapCHRange,
	StrCpyToWorldCHRange,
	StrCpyToGlobalCHRange,
	PushFunction,
	CallStack,
	ScriptWaitNamed,
	TranslationRange3,
	GotoStack,
	AssignScriptArray,
	PushScriptArray,
	AddScriptArray,
	SubScriptArray,
	MulScriptArray,
	DivScriptArray,
	ModScriptArray,
	IncScriptArray,
	DecScriptArray,
	AndScriptArray,
	EorScriptArray,
	OrScriptArray,
	LsScriptArray,
	RsScriptArray,
	PrintScriptCharArray,
	PrintScriptCHRange,
	StrCpyToScriptCHRange,
	LSpec5Ex,
	LSpec5ExResult,
	TranslationRange4,
	TranslationRange5,
}

const COUNT: usize = (PCode::TranslationRange5 as usize) + 1;
