//! The primary interface for quick introspection into the VFS.

/*

Copyright (C) 2022 ***REMOVED***

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

use regex::Regex;

use super::{
	entry::{Entry, EntryKind},
	Handle, VirtualFs,
};

/// The primary interface for quick introspection into the VFS;
/// provides read access to one entry.
///
/// These are cheap to create and clone, but not meant to be stored. See [`Handle`]
/// for a type that can exist apart from the VFS; they can be generated by calling
/// [`handle`](Self::handle).
#[derive(Debug, Clone)]
pub struct FileRef<'vfs> {
	pub vfs: &'vfs VirtualFs,
	pub entry: &'vfs Entry,
	pub index: usize,
}

impl std::ops::Deref for FileRef<'_> {
	type Target = Entry;

	fn deref(&self) -> &Self::Target {
		self.entry
	}
}

impl<'vfs> FileRef<'vfs> {
	/// The returned iterator will be empty if requesting the children of a leaf node.
	pub fn children(&'vfs self) -> impl Iterator<Item = &'vfs Entry> {
		match &self.entry.kind {
			EntryKind::Directory(children) => super::Iter {
				vfs: self.vfs,
				elements: children,
				current: 0,
			},
			_ => super::Iter {
				vfs: self.vfs,
				elements: &[],
				current: 0,
			},
		}
	}

	/// Note: non-recursive. Panics if used on a leaf node.
	/// Check to ensure it's a directory beforehand.
	#[must_use]
	pub fn contains_regex(&self, regex: &Regex) -> bool {
		self.children().any(|h| regex.is_match(h.file_name()))
	}

	/// Returns the number of child entries this entry has, if it's a directory.
	/// If it's a leaf node, returns 0.
	#[must_use]
	pub fn child_count(&self) -> usize {
		match &self.entry.kind {
			EntryKind::Directory(children) => children.len(),
			_ => 0,
		}
	}

	#[must_use]
	pub fn handle(&self) -> Handle {
		Handle {
			index: self.index,
			generation: self.vfs.generation,
		}
	}
}
