//! Function indices.
//!
//! Assume all code within is derived from GZDoom-original source unless
//! explicitly stated otherwise.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) enum Function {
	GetLineUdmfInt = 1,
	GetLineUdmfFixed,
	GetThingUdmfInt,
	GetThingUdmfFixed,
	GetSectorUdmfInt,
	GetSectorUdmfFixed,
	GetSideUdmfInt,
	GetSideUdmfFixed,
	GetActorVelX,
	GetActorVelY,
	GetActorVelZ,
	SetActivator,
	SetActivatorToTarget,
	GetActorViewHeight,
	GetChar,
	GetAirSupply,
	SetAirSupply,
	SetSkyScrollSpeed,
	GetArmorType,
	SpawnSpotForced,
	SpawnSpotFacingForced,
	CheckActorProperty,
	SetActorVelocity,
	SetUserVariable,
	GetUserVariable,
	RadiusQuake2,
	CheckActorClass,
	SetUserArray,
	GetUserArray,
	SoundSequenceOnActor,
	SoundSequenceOnSector,
	SoundSequenceOnPolyobj,
	GetPolyobjX,
	GetPolyobjY,
	CheckSight,
	SpawnForced,
	AnnouncerSound,
	SetPointer,
	NamedExecute,
	NamedSuspend,
	NamedTerminate,
	NamedLockedExecute,
	NamedLockedExecuteDoor,
	NamedExecuteWithResult,
	NamedExecuteAlways,
	UniqueTid,
	IsTidUsed,
	Sqrt,
	FixedSqrt,
	VectorLength,
	SetHudClipRect,
	SetHudWrapWidth,
	SetCVar,
	GetUserCVar,
	SetUserCVar,
	GetCVarString,
	SetCVarString,
	GetUserCVarString,
	SetUserCVarString,
	LineAttack,
	PlaySound,
	StopSound,
	StrCmp,
	StriCmp,
	StrLeft,
	StrRight,
	StrMid,
	GetActorClass,
	GetWeapon,
	SoundVolume,
	PlayActorSound,
	SpawnDecal,
	CheckFont,
	DropItem,
	CheckFlag,
	SetLineActivation,
	GetLineActivation,
	GetActorPowerupTics,
	ChangeActorAngle,
	ChangeActorPitch,
	GetArmorInfo,
	DropInventory,
	PickActor,
	IsPointerEqual,
	CanRaiseActor,
	SetActorTeleFog,
	SwapActorTeleFog,
	SetActorRoll,
	ChangeActorRoll,
	GetActorRoll,
	QuakeEx,
	Warp,
	GetMaxInventory,
	SetSectorDamage,
	SetSectorTerrain,
	SpawnParticle,
	SetMusicVolume,
	CheckProximity,
	CheckActorState,
	// Zandronum ///////////////////////////////////////////////////////////////
	// 100 : ResetMap(0),
	// 101 : PlayerIsSpectator(1),
	// 102 : ConsolePlayerNumber(0),
	// 103 : GetTeamProperty(2),
	// 104 : GetPlayerLivesLeft(1),
	// 105 : SetPlayerLivesLeft(2),
	// 106 : KickFromGame(2),
	CheckClass = 200,
	DamageActor,
	SetActorFlag,
	SetTranslation,
	GetActorFloorTexture,
	GetActorFloorTerrain,
	StrArg,
	Floor,
	Round,
	Ceil,
	ScriptCall,
	StartSlideshow,
	GetSectorHealth,
	GetLineHealth,
	SetSubtitleNumber,
	// Eternity Engne
	GetLineX = 300,
	GetLineY,
	// Hardware renderer
	SetSectorGlow = 400,
	SetFogDensity,
	// ZDaemon
	GetTeamScore = 19620, // (int team)
	SetTeamScore,         // (int team, int value
}
