// Auto-generated by Tree-sitter 2024-09-30T17:21:23.303905Z

#include "doomtools/wadmerge/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 1
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym__ident = 1,
  aux_sym_clear_command_token1 = 2,
  aux_sym_create_command_token1 = 3,
  aux_sym_create_command_token2 = 4,
  aux_sym_echo_command_token1 = 5,
  aux_sym_echo_command_token2 = 6,
  aux_sym_echo_command_token3 = 7,
  aux_sym_end_command_token1 = 8,
  sym__string_literal = 9,
  sym_line_comment = 10,
  anon_sym_LF = 11,
  anon_sym_CR_LF = 12,
  anon_sym_CR = 13,
  sym_source_file = 14,
  sym__line = 15,
  sym_clear_command = 16,
  sym_create_command = 17,
  sym_echo_command = 18,
  sym_end_command = 19,
  sym_symbol = 20,
  sym__trailer = 21,
  sym__newline = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_create_command_repeat1 = 24,
  aux_sym_echo_command_repeat1 = 25,
  alias_sym_echo_text = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__ident] = "_ident",
  [aux_sym_clear_command_token1] = "clear",
  [aux_sym_create_command_token1] = "create",
  [aux_sym_create_command_token2] = "iwad",
  [aux_sym_echo_command_token1] = "echo",
  [aux_sym_echo_command_token2] = "echo_command_token2",
  [aux_sym_echo_command_token3] = "echo_command_token3",
  [aux_sym_end_command_token1] = "end",
  [sym__string_literal] = "_string_literal",
  [sym_line_comment] = "line_comment",
  [anon_sym_LF] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_CR] = "\r",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_clear_command] = "clear_command",
  [sym_create_command] = "create_command",
  [sym_echo_command] = "echo_command",
  [sym_end_command] = "end_command",
  [sym_symbol] = "symbol",
  [sym__trailer] = "_trailer",
  [sym__newline] = "_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_create_command_repeat1] = "create_command_repeat1",
  [aux_sym_echo_command_repeat1] = "echo_command_repeat1",
  [alias_sym_echo_text] = "echo_text",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__ident] = sym__ident,
  [aux_sym_clear_command_token1] = aux_sym_clear_command_token1,
  [aux_sym_create_command_token1] = aux_sym_create_command_token1,
  [aux_sym_create_command_token2] = aux_sym_create_command_token2,
  [aux_sym_echo_command_token1] = aux_sym_echo_command_token1,
  [aux_sym_echo_command_token2] = aux_sym_echo_command_token2,
  [aux_sym_echo_command_token3] = aux_sym_echo_command_token3,
  [aux_sym_end_command_token1] = aux_sym_end_command_token1,
  [sym__string_literal] = sym__string_literal,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_CR] = anon_sym_CR,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_clear_command] = sym_clear_command,
  [sym_create_command] = sym_create_command,
  [sym_echo_command] = sym_echo_command,
  [sym_end_command] = sym_end_command,
  [sym_symbol] = sym_symbol,
  [sym__trailer] = sym__trailer,
  [sym__newline] = sym__newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_create_command_repeat1] = aux_sym_create_command_repeat1,
  [aux_sym_echo_command_repeat1] = aux_sym_echo_command_repeat1,
  [alias_sym_echo_text] = alias_sym_echo_text,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_clear_command_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_create_command_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_create_command_token2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_echo_command_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_echo_command_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_echo_command_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_end_command_token1] = {
    .visible = true,
    .named = false,
  },
  [sym__string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_clear_command] = {
    .visible = true,
    .named = true,
  },
  [sym_create_command] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_command] = {
    .visible = true,
    .named = true,
  },
  [sym_end_command] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__trailer] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_create_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_echo_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_echo_text] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_iwad_qual = 1,
  field_symbol = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_iwad_qual] = "iwad_qual",
  [field_symbol] = "symbol",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_symbol, 1},
  [1] =
    {field_iwad_qual, 2},
    {field_symbol, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [2] = alias_sym_echo_text,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_echo_command_repeat1, 2,
    aux_sym_echo_command_repeat1,
    alias_sym_echo_text,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 10,
  [25] = 25,
  [26] = 26,
};

static inline bool sym__ident_character_set_1(int32_t c) {
  return (c < 8192
    ? (c < 133
      ? (c < 28
        ? (c >= 11 && c <= '\f')
        : c <= 31)
      : (c <= 133 || c == 5760))
    : (c <= 8198 || (c < 8287
      ? (c < 8232
        ? (c >= 8200 && c <= 8202)
        : c <= 8233)
      : (c <= 8287 || c == 12288))));
}

static inline bool anon_sym_LF_character_set_1(int32_t c) {
  return (c < 8192
    ? (c < 133
      ? (c < 28
        ? (c >= '\t' && c <= '\f')
        : c <= ' ')
      : (c <= 133 || c == 5760))
    : (c <= 8198 || (c < 8287
      ? (c < 8232
        ? (c >= 8200 && c <= 8202)
        : c <= 8233)
      : (c <= 8287 || c == 12288))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(62);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(50);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(43);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(39);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1)
      if (sym__ident_character_set_1(lookahead)) ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\r' < lookahead)) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(10);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 10:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(7);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == 11 ||
          (28 <= lookahead && lookahead <= ' ')) ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(59);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 18:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(62);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (anon_sym_LF_character_set_1(lookahead)) SKIP(18)
      END_STATE();
    case 19:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(19)
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(33);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(20)
      if (sym__ident_character_set_1(lookahead)) ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_clear_command_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_clear_command_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_create_command_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_create_command_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_create_command_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_create_command_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_echo_command_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_echo_command_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_echo_command_token2);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_echo_command_token3);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_end_command_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_end_command_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(50);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(43);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(49);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(47);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '"') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__ident);
      if (sym__ident_character_set_1(lookahead)) ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__ident);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__string_literal);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 20},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__ident] = ACTIONS(1),
    [aux_sym_clear_command_token1] = ACTIONS(1),
    [aux_sym_create_command_token1] = ACTIONS(1),
    [aux_sym_create_command_token2] = ACTIONS(1),
    [aux_sym_echo_command_token1] = ACTIONS(1),
    [aux_sym_end_command_token1] = ACTIONS(1),
    [sym__string_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(25),
    [sym__line] = STATE(12),
    [sym_clear_command] = STATE(12),
    [sym_create_command] = STATE(12),
    [sym_echo_command] = STATE(12),
    [sym_end_command] = STATE(12),
    [sym__newline] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_clear_command_token1] = ACTIONS(5),
    [aux_sym_create_command_token1] = ACTIONS(7),
    [aux_sym_echo_command_token1] = ACTIONS(9),
    [aux_sym_end_command_token1] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(13),
    [anon_sym_LF] = ACTIONS(15),
    [anon_sym_CR_LF] = ACTIONS(15),
    [anon_sym_CR] = ACTIONS(17),
  },
  [2] = {
    [sym__line] = STATE(20),
    [sym_clear_command] = STATE(20),
    [sym_create_command] = STATE(20),
    [sym_echo_command] = STATE(20),
    [sym_end_command] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_clear_command_token1] = ACTIONS(5),
    [aux_sym_create_command_token1] = ACTIONS(7),
    [aux_sym_echo_command_token1] = ACTIONS(9),
    [aux_sym_end_command_token1] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(19),
    [anon_sym_CR_LF] = ACTIONS(19),
    [anon_sym_CR] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym_create_command_token2,
    ACTIONS(29), 1,
      aux_sym_echo_command_token3,
    STATE(4), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(31), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [19] = 4,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      aux_sym_echo_command_token3,
    STATE(7), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(37), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [35] = 4,
    ACTIONS(35), 1,
      aux_sym_echo_command_token3,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(41), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [51] = 4,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      aux_sym_echo_command_token3,
    STATE(8), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(47), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [67] = 4,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      aux_sym_echo_command_token3,
    STATE(7), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(54), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [83] = 4,
    ACTIONS(35), 1,
      aux_sym_echo_command_token3,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(58), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [99] = 4,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      aux_sym_echo_command_token3,
    STATE(5), 2,
      sym__trailer,
      aux_sym_create_command_repeat1,
    ACTIONS(64), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [115] = 2,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 5,
      aux_sym_create_command_token2,
      aux_sym_echo_command_token3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [126] = 4,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      aux_sym_echo_command_token3,
    STATE(11), 1,
      aux_sym_echo_command_repeat1,
    ACTIONS(75), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [141] = 5,
    ACTIONS(17), 1,
      anon_sym_CR,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(15), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [158] = 5,
    ACTIONS(17), 1,
      anon_sym_CR,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(15), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [175] = 4,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      aux_sym_echo_command_token3,
    STATE(11), 1,
      aux_sym_echo_command_repeat1,
    ACTIONS(83), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [190] = 4,
    ACTIONS(81), 1,
      aux_sym_echo_command_token3,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      aux_sym_echo_command_repeat1,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [205] = 5,
    ACTIONS(17), 1,
      anon_sym_CR,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(15), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [222] = 5,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_CR,
    STATE(2), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(93), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
  [239] = 2,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      aux_sym_echo_command_token3,
    ACTIONS(101), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_CR,
  [249] = 2,
    ACTIONS(105), 1,
      anon_sym_CR,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [258] = 2,
    ACTIONS(107), 1,
      anon_sym_CR,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_LF,
      anon_sym_CR_LF,
  [267] = 3,
    ACTIONS(109), 1,
      sym__ident,
    ACTIONS(111), 1,
      sym__string_literal,
    STATE(23), 1,
      sym_symbol,
  [277] = 3,
    ACTIONS(113), 1,
      sym__ident,
    ACTIONS(115), 1,
      sym__string_literal,
    STATE(3), 1,
      sym_symbol,
  [287] = 2,
    ACTIONS(117), 1,
      aux_sym_echo_command_token3,
    STATE(19), 1,
      sym__trailer,
  [294] = 1,
    ACTIONS(66), 1,
      aux_sym_echo_command_token3,
  [298] = 1,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
  [302] = 1,
    ACTIONS(121), 1,
      aux_sym_echo_command_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 19,
  [SMALL_STATE(5)] = 35,
  [SMALL_STATE(6)] = 51,
  [SMALL_STATE(7)] = 67,
  [SMALL_STATE(8)] = 83,
  [SMALL_STATE(9)] = 99,
  [SMALL_STATE(10)] = 115,
  [SMALL_STATE(11)] = 126,
  [SMALL_STATE(12)] = 141,
  [SMALL_STATE(13)] = 158,
  [SMALL_STATE(14)] = 175,
  [SMALL_STATE(15)] = 190,
  [SMALL_STATE(16)] = 205,
  [SMALL_STATE(17)] = 222,
  [SMALL_STATE(18)] = 239,
  [SMALL_STATE(19)] = 249,
  [SMALL_STATE(20)] = 258,
  [SMALL_STATE(21)] = 267,
  [SMALL_STATE(22)] = 277,
  [SMALL_STATE(23)] = 287,
  [SMALL_STATE(24)] = 294,
  [SMALL_STATE(25)] = 298,
  [SMALL_STATE(26)] = 302,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_command, 2, .production_id = 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_create_command, 2, .production_id = 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_command, 3, .production_id = 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_create_command, 3, .production_id = 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_command, 4, .production_id = 2),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_create_command, 4, .production_id = 2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_command, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_command, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_create_command_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_create_command_repeat1, 2), SHIFT_REPEAT(7),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_create_command_repeat1, 2),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_command, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_command, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_create_command, 3, .production_id = 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_create_command, 3, .production_id = 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_echo_command_repeat1, 2),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_echo_command_repeat1, 2), SHIFT_REPEAT(18),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_echo_command_repeat1, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_command, 3, .production_id = 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_command, 3, .production_id = 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_command, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_command, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_echo_command_repeat1, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_echo_command_repeat1, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clear_command, 3, .production_id = 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_clear_command, 3, .production_id = 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [119] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_wadmerge(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__ident,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
